# Generated by Django 2.2.7 on 2020-04-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0015_auto_20200403_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='agravo',
        ),
        migrations.DeleteModel(
            name='Agravo',
        ),
    ]
