# Generated by Django 2.2.7 on 2020-04-05 20:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapa', '0016_auto_20200405_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='doencas_pre_existentes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Diabetes'), (2, 'Doenças Cardiovasculares'), (3, 'Doenças Respiratórias'), (4, 'Doenca Renal Cronica'), (5, 'Hipertensao Arterial')], default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='sinais_clinicos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Tosse'), (2, 'Febre'), (3, 'Cansaço'), (4, 'Congestão Nasal'), (5, 'Diarreia'), (6, 'Dores corporais'), (7, 'Dificuldade para respirar')], default=None, max_length=13),
        ),
    ]
